version: '3.8'

services:
  app:
    build: .
    container_name: synapse_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    environment:
      # Важно: тут root/root_password, проверь свои application.properties!
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/synapse_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"

      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password123

  db:
    image: postgres:15
    container_name: synapse-db
    environment:
      POSTGRES_DB: synapse_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  redis:
    image: redis:7-alpine
    container_name: synapse-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  minio_data:
  postgres_data: