spring.application.name=Synapse

spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/synapse_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket=task-files